flyway.locations=filesystem:db/migration
flyway.sqlMigrationPrefix=V
flyway.sqlMigrationSeparator=__
flyway.sqlMigrationSuffixes=.sql
flyway.placeholderReplacement=true
flyway.placeholders.defaultTenantId=system
